### ISSUE TITLE
Bundle addon versions out of date

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#316]
Is there some way that we could show that a specific addon version on a bundle is not the latest?

Or should it be the other way round, show if the version is the latest. 

What is the use case here?

Thanks @BigRoy 

![image](https://github.com/ynput/ayon-frontend/assets/49156310/b0a128ff-1073-4965-a0d2-cbc0ae30d4bf)

**Comment by BigRoy** [comment]
The use case for me is so that when investigating my current production bundle I can quickly see whether there's anything worth to "**Duplicate and Edit**" my bundle for to support a newer version of an installed addon - which seems to be the typical (and only?) case when I'm actually generating new bundles.

**Comment by Innders** [comment]
> see whether there's anything worth to "**Duplicate and Edit**" my bundle for to support a newer version of an installed addon.

- Knowing if the bundle as a whole is outdated.
- Knowing which addons are outdated so you can decide if the update is worth/necessary.

You will only ever see outdated addons that have already been installed from the market. So if there's a new version on the market available then you won't see that here, until it's installed. 

You can actually already see what addons are outdated in your prod bundle and outdated on the server. Maybe that would be a better way to solve this issue and gets users into the habit of checking the market for updates.

![image](https://github.com/ynput/ayon-frontend/assets/49156310/653b10c9-762f-4843-9b80-50a93690febe)

**Comment by BigRoy** [comment]
> You will only ever see outdated addons that have already been installed from the market. So if there's a new version on the market available then you won't see that here, until it's installed.

Correct - but more often than not I'm uploading addons manually to my server since I'm also developing. I'm often on a newer version than the latest version available on the Addon market to begin with.

**Comment by Innders** [comment]
Maybe it's as simple as an icon next to any version that isn't the latest.

![image](https://github.com/ynput/ayon-frontend/assets/49156310/4cc43eba-ddf3-4508-a348-968f1fa4dc10)

![image](https://github.com/ynput/ayon-frontend/assets/49156310/d955c16b-3182-4272-97a5-378dc49a9b34)

**Comment by BigRoy** [comment]
I like the up arrow since it's not as negative as the other one. The other one seems to hint something may be broken.
I do directly get the tendency to "click" it - so maybe turn it slightly dimmed to avoid it looking clickable since I suspect it's not clickable.
Bonus points for being able to list the newer version names in a tooltip when hovering the icon.
