### ISSUE TITLE
Show new team as a dialog popup

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#334]
- [x] Show new team form in a popup modal.
- [x] In the modal have the users on the left hand side so they can be selected for the team.

Users table should only have one column with profile image and full name.

![image](https://github.com/ynput/ayon-frontend/assets/49156310/b3ddb86d-6555-485e-82e9-9d2c644e12a4)

**Comment by Innders** [comment]
Just to clarify, it should be like creating a new user. Dialog popups up.

On left there is a list of users to select for adding to the new team. On the right the form inputs for the team.

![image](https://github.com/ynput/ayon-frontend/assets/49156310/c4569be1-a75b-4fda-a372-225527c49811)

**Comment by LudoHolbik** [comment]
@Innders Is this more like it ? 

https://github.com/ynput/ayon-frontend/assets/16327908/2c644935-fbec-4ca3-97f2-dfd6ef64a409

**Comment by LudoHolbik** [comment]
@Innders Is this more like it ?



https://github.com/ynput/ayon-frontend/assets/16327908/98dfab6f-96c6-4172-943c-93d43078bec5

**Comment by LudoHolbik** [comment]
@Innders I have requested review for PR of updated version:
- I have added searchbar for users
- Moving buttons turned out to be less straightforward than I thought, they are in the child element of a parent that is wrapped in dialog. It seemed to me that it would be a bit tricky so what I did was some style changes that visually achieve the same. Is this ok with you ?


https://github.com/ynput/ayon-frontend/assets/16327908/537464fb-5fe2-42ae-aca8-6a99371885ae
