### ISSUE TITLE
Anatomy: copy paste function is not doing anything

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ayon-frontend#426]
# To replicate:
1. Go to your project Anatomy tab 
2. Go to Templates 
3. Go to Others
4. Add one more tempate and save
5. Copy on the Others category
6. Go to other project which is not having the new tempalate in Others
7. Paste on the Others category and see that nothing had been copied

**Comment by martastain** [comment]
Thanks. Confirmed. It seems to be caused by the fact that the target list is empty for some reason.

When you do all the steps you described, but after the 6th step you click the (+) button to create an empty, unsaved record and then "overwrite" that list with the value you have in your clipboard, it works.

Pasting over an empty list throws this
![image](https://github.com/ynput/ayon-frontend/assets/5007200/ab98155d-18f0-4aa7-be90-e87693d12311)
