### ISSUE TITLE
Projects: Switching between project and home

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#474]
## Story

You open a project and then want to see your tasks on that project. You click on home and the project is preselected so you can view the tasks.

## Solution

When moving back to home, the project should be selected.

**Comment by dee-ynput** [comment]
Is there some information missing for this? It looks pretty straighforward to me 🙂

**Comment by BigRoy** [comment]
I did have this discussion with Luke. Luke said:

> Question: 
> 
> In home you have 3 projects selected.
> You open one of those selected projects.
> You go back to home.
> 
> a) All 3 projects are still selected because the opened project was in the original selection
> b) Now only the 1 opened project is selected
> I vote **a**

My response was:

> Yes, agree - in that scenario a is nicer.
> So maybe, if the project is in the multiselection - change nothing. If not, select the project.

Not sure if that makes the implementation more involved.

**Comment by dee-ynput** [comment]
I guess I've never seen the issue because I'm bouble-clicking in the Home's view project selector to go to a project (which deselects all other projects before jumping) 😅 

I would have voted B) because you're coming back from a single project and it would feel natural to stay in the same context.
But multiselection is so amazing in AYON I'll totally trust your decision! ✊🔥

Also, both A) and B) are better than the current situation which just keeps the project selection as it was before you left, even if you have navigated to some other project(s) on the way... :^_^:

So, good to go ! 👍
