### ISSUE TITLE
Feed: Emoji reaction

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-frontend#603]
## Story

As an user, I want to quickly express a reaction to an entry in an activity feed my setting an emoji on it.

(Something similar to Github, Discord, Slack, Whatsapp, etc...)

origin: [discord](https://discord.com/channels/517362899170230292/517380724618428416/1257357167212630106)

**Comment by Innders** [comment]
A simple like button could be enough to signal that "I have read and understood this comment". It would be a lot easier to implement as well.

What do you think @mkolar ?

![image](https://github.com/user-attachments/assets/0e6e25e8-baa3-4a93-b675-0e5603eed74f)

**Comment by mkolar** [comment]
I agree that the simpler the better. I'd argue that it might even be better to use an eye icon instead of like.

Like indicates emotion, where now everyone expects multiple options nowadays, but eye could just say... I acknowledge I've seen this.

Unless we eventually actually add... Seen inidcator

**Comment by BigRoy** [comment]
I personally enjoy setting a specific emotion as a reaction to a comment - but it may make it a bit too much of a social platform.

For context:
"Seen indicators" are messy in that, yes... I may have visited the page and scrolled past it, but have not read it. Or, often it gives me the urge to _not_ open e.g. a certain chat because the seen notification may hint to the other person that I will be acting upon it rather sooner than later, but often times I read it, and maybe mark something to remind me later or "mark as unread" if I don't want to deal with things now.

**Comment by Innders** [comment]
I really like how github does it, enough options to convey your emotion towards the comment but not so many it becomes silly social media.

![image](https://github.com/user-attachments/assets/10366e1a-ac29-4f65-8e30-21b88ebcfe68)

![image](https://github.com/user-attachments/assets/1b923f98-1cf1-4f87-ae85-dbf45e9beddf)

![image](https://github.com/user-attachments/assets/933be27c-b60d-4cd9-8d6a-989a580bbc40)
