### ISSUE TITLE
Editor: Assign a user to many tasks at once whilst preserving the other assignees.

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#651]
## Story

Today I wanted to add an assignee to many tasks for some that other artists were previously assigned to. I wanted to add the user as an additional assignee.

### Problems

When multiselecting many tasks, and then adding a user the "assignees" for the selected task will be replaced with the result of the dropdown - which initializes to the users of ONE OF THE tasks in the selection - meaning I'm suddenly now also overriding the other assignees instead of just adding the one user.

### Proposal

Preferablu I'd be able to just make "edits" like 'add this' or 'remove this' even with multiselection?

## TODO

- [ ] Allow 'add/remove' edits when multiselecting for e.g. assignees instead of 'replacing' edits of the full value for all entries.

**Comment by mkolar** [comment]
This is actually how vast majority of systems out there work. If you're additive, then you can't lower the number of assignees in bulk, or remove assignees really. I'd consider this the correct behaviour. 

However, the initial values should be just empty, rather than a set of all assignees which it is now. (not one of the tasks)

Alternativelly it could be pre-populated with the assignee list of the last selected task. That way you'd have full control over it.

**Comment by mkolar** [comment]
Just a note though, that this should probably be part of the `Teams as users` epic that will need some work to be done on the assignee component.

**Comment by Innders** [comment]
https://github.com/ynput/ayon-react-components/issues/174
