### ISSUE TITLE
Bootstrap: info about used linux variant

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-frontend#712]
## Story
When running bootstrap process, platform selection allows to select `windows` | `macos` | `linux`.
With linux selection, I'll always automatically get rocky9 specific binaries of launcher and dependency packages. Currently, we don't have any mechanims on pipeline side to differentiate, so at least information about what will be used should be presented.

### Problems
User expirience after bootstrapping on linux environment other than Rocky 9 can be confusing as ayon launcher and/or dependency package won't probably work.

### Proposal
We should show information about currently supported linux platform at least until we can provide the selection of different linux variants. Something along the line: "This will install Rocky 9 specific environment that should be compatible with all EL9 linux variants".

## TODO
If we ever decide on extended support for mac - Intel AND ARM-based, we will have to provide something similar there. Currently it could use some information too, like that current support is limited to Intel based platform (or using Rosetta emulation).

**Comment by Innders** [comment]
The only information in the release that relates to rocky-9 is the filename and MacOS has nothing to help with Intel/ARM.
![image](https://github.com/user-attachments/assets/3a9cb97a-09e8-406d-981c-958fb4f05eea)

Because this can't be pulled from the release itself can the "notes" be hardcoded. If so what exactly should they say?

![image](https://github.com/user-attachments/assets/d4c8287a-f029-458c-b41e-3d82cab5f0c7)

**Comment by Innders** [comment]
> what exactly should they say?
@antirotor could you help out please so that @flynput can implement it.
