### ISSUE TITLE
Settings: Search all settings

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#870]
First step in better filtering of settings is to do a settings wide (all addons) search. From that the user can then move onto the second step of filtering the search results.

This PR will only handle the first step of searching.

- Search matches, field names, values and descriptions (basically everything).
- Big search bar at the top of the page.
- When searching remove the selection of addons in the left panel and search through all addons.
- If an addon is selected in the left panel then the search becomes filtered to only the selected addons.

![image](https://github.com/user-attachments/assets/4ad00ecf-4fa8-43ec-8b1b-88d8c83fb1ba)

**Comment by mkolar** [comment]
@flynput @Innders is this stuck on something specific or just waiting for capacity guys?

**Comment by flynput** [comment]
> @flynput @Innders is this stuck on something specific or just waiting for capacity guys?

It's been set aside last week due to user/project/access groups assignment having higher priority. 
I resumed work on it yesterday afternoon and it's close to being ready, the only gotchas being json-schema complexity which makes mapping tricky and multi addon filtering. If all goes well, tomorrow we'll have a non-draft PR for it.
